on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: untillpro-test/air-js-action@master
    - name: Build
      env:
        GOOS: windows
        GOARCH: 386
      run: |
        go build ./...
        go test ./...
    - name: Merge to master
      run: |
        if [ "$GITHUB_REF" = 'refs/heads/develop' ]; then
          git fetch origin master
          git checkout master
          git merge $GITHUB_SHA
          git push 2>&1
        fi
    - uses: actions/upload-artifact@v1
      with:
      name: air-js-action-test
      path: air-js-action-test.exe
